### ISSUE TITLE
Page jumps to Pathway Diagram on page load

### ISSUE THREAD

**Issue by tschaka1904** [Complex-Portal/complex-portal-view#189] opened 2018-11-20 14:18 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search existing issues for a similar problems/requests
[ ] feature request
[ ] support request => Please do not submit support request here, instead see: http://www.ebi.ac.uk/support/intact
```

**Current behaviour**
When opening a Complex that has a Pathway Diagram, the viewport is jumping to the Pathway Diagram once it is loading. 

This is a bug that only seems to happen in Safari. At least it doesn't happen in chrome. I suspect that the Pathway Diagram is triggering some sort of event. 

**Expected behaviour**
The page should not jump to any content of the page, without the users action. 

**Minimal reproduction of the problem with instructions**
![2018-11-20_15-08-09](https://user-images.githubusercontent.com/5269116/48779003-f5745b00-ecd6-11e8-8d0f-b7ad801bad02.gif)

**Please tell us about your environment:**
Mac OS using Safari Version 11.0.3 

###### Just a few guidelines for how to write effective and good GitHub issues: [HOW WE WRITE GITHUB ISSUES](https://wiredcraft.com/blog/how-we-write-our-github-issues/)

**Comment by bmeldal** [comment] 2018-11-20 14:47
Thanks, Max. This has been happening for ages but I can't find an existing Jira ticket so created one. Closing this as I have moved the issue.

Good to know to still have you as a user!

**Closed as completed by bmeldal** 2018-11-20 14:47 UTC

**Comment by tschaka1904** [comment] 2018-11-20 15:25
Haha! Once in a while I like to checkout what going on with the front-end development. ;-) 

It might be worth talking to the guys in Reactome, as this might be an easy fix. When you open https://reactome.org/dev/diagram/js#API (on Safari) and scroll down very quickly, you'll see that it jumps back up again once the Diagram is loaded. This makes me believe that this is not a CP issue.

**Comment by noedelta** [comment] 2018-11-20 15:38
Hi Max,

Thanks for helping :D

I checked and I think the problem is that the focus of the cursor (to start typing) positions in the Reactome Diagram search box and then it scrolls automatically to there. We will try to look in to it.

Regards,

Noe
